import { NextResponse } from "next/server";
import sgMail from "@sendgrid/mail";

sgMail.setApiKey(process.env.SENDGRID_COMPLIANCE_API_KEY!);

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const {
      userEmail,
      itemName,
      expiresDate,
      shopName,
      artistName,
      dashboardUrl,
    } = body;

    if (!userEmail) {
      return NextResponse.json(
        { error: "Missing user email." },
        { status: 400 }
      );
    }

    if (!itemName) {
      return NextResponse.json(
        { error: "Missing compliance item name." },
        { status: 400 }
      );
    }

    await sgMail.send({
      from: {
        email: "compliance@artistprotectionalliance.com",
        name: "APA Compliance",
      },
      to: userEmail,
      subject: `Compliance Reminder: ${itemName}`,
      html: `
        <div style="font-family: Arial, sans-serif; background:#f7f2ea; padding:24px;">
          <div style="max-width:640px; margin:0 auto; background:#ffffff; border-radius:18px; overflow:hidden; border:1px solid #eadfce;">
            
            <div style="background:#1f2f2b; padding:24px;">
              <h1 style="margin:0; color:#ffffff; font-size:24px;">
                Compliance Reminder
              </h1>
              <p style="margin:8px 0 0; color:#ffffff; font-size:14px;">
                Artist Protection Alliance
              </p>
            </div>

            <div style="padding:28px;">
              <p style="font-size:16px; color:#2d2d2d; margin-top:0;">
                Hi${artistName ? ` ${artistName}` : ""},
              </p>

              <p style="font-size:16px; color:#2d2d2d; line-height:1.6;">
                This is a reminder that the following compliance item needs your attention:
              </p>

              <div style="background:#f7f2ea; border-left:5px solid #c47a3c; padding:18px; border-radius:12px; margin:22px 0;">
                <p style="margin:0; font-size:18px; color:#1f2f2b; font-weight:bold;">
                  ${itemName}
                </p>
                <p style="margin:8px 0 0; color:#5f5a50;">
                  Expiration / renewal date: <strong>${expiresDate || "Not listed"}</strong>
                </p>
                ${
                  shopName
                    ? `<p style="margin:8px 0 0; color:#5f5a50;">Shop: <strong>${shopName}</strong></p>`
                    : ""
                }
              </div>

              <p style="font-size:16px; color:#2d2d2d; line-height:1.6;">
                Please review your dashboard and update this item if it has already been completed or renewed.
              </p>

              ${
                dashboardUrl
                  ? `
                  <div style="margin:28px 0; text-align:center;">
                    <a href="${dashboardUrl}" style="background:#c47a3c; color:#ffffff; text-decoration:none; padding:14px 20px; border-radius:999px; font-weight:bold; display:inline-block; text-align:center;">
                      Open Compliance Dashboard
                    </a>
                  </div>
                  `
                  : ""
              }

              <p style="font-size:13px; color:#777; line-height:1.5; margin-top:30px;">
                This reminder was generated by Artist Protection Alliance to help tattoo professionals stay organized with licensing, certification, and renewal tracking.
              </p>
            </div>
          </div>
        </div>
      `,
    });

    return NextResponse.json({
      success: true,
      message: "Compliance reminder sent successfully.",
    });
  } catch (error: any) {
    console.error("SENDGRID COMPLIANCE EMAIL ERROR:", error);

    return NextResponse.json(
      {
        error: "Failed to send compliance reminder.",
        details: error?.message || error,
      },
      { status: 500 }
    );
  }
}
