-- 1. MEMBERS
create table if not exists members (
  id bigint generated by default as identity primary key,
  name text not null,
  email text
);

-- 2. COMPLIANCE ITEM LIBRARY
create table if not exists compliance_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text,
  default_expiry_months integer,
  applies_to_state text,
  applies_to_county text,
  applies_to_city text,
  is_required boolean default true,
  required_level text default 'mandatory',
  reminder_days integer[] default array[90, 60, 30],
  active boolean default true,
  created_at timestamptz default now()
);

-- 3. USER COMPLIANCE TRACKING
create table if not exists user_compliance_items (
  id bigint generated by default as identity primary key,
  user_id bigint references members(id) on delete cascade,
  compliance_item_id bigint references compliance_items(id) on delete cascade,
  location_state text,
  location_county text,
  status text default 'active',
  completed_date date,
  expires_date date,
  reminder_enabled boolean default true,
  next_reminder_date date,
  created_at timestamptz default now()
);

-- 4. TEST MEMBER
insert into members (name, email)
values ('Kristen', 'kristen@test.com');

-- 5. COMPLIANCE ITEM TEMPLATES
insert into compliance_items
(
  name,
  description,
  category,
  default_expiry_months,
  applies_to_state,
  applies_to_county,
  applies_to_city,
  is_required,
  required_level,
  reminder_days
)
values
('Bloodborne Pathogen Certification', 'Tracks completion and expiration of bloodborne pathogen training.', 'training', 12, 'AZ', 'Maricopa', null, true, 'mandatory', array[90, 60, 30]),
('Sharps Disposal Contract', 'Tracks proof of sharps disposal or medical waste service.', 'sanitation', 12, 'AZ', 'Maricopa', null, true, 'mandatory', array[90, 60, 30]),
('Shop Permit', 'Tracks tattoo shop or studio permit status.', 'license', 12, 'AZ', 'Maricopa', null, true, 'mandatory', array[90, 60, 30]),
('Autoclave Maintenance Log', 'Tracks sterilization equipment maintenance documentation.', 'sanitation', 1, 'AZ', 'Maricopa', null, true, 'mandatory', array[30, 14, 7]),
('Consent Form System', 'Tracks whether the artist or shop has an active consent form process.', 'documentation', 12, 'AZ', 'Maricopa', null, true, 'mandatory', array[90, 60, 30]),
('Insurance Policy', 'Tracks professional liability or business insurance renewal.', 'insurance', 12, 'AZ', 'Maricopa', null, false, 'recommended', array[90, 60, 30]),
('Inspection Readiness Checklist', 'Tracks internal readiness for health department or regulatory inspection.', 'inspection', 6, 'AZ', 'Maricopa', null, false, 'recommended', array[60, 30, 14]),
('Infection Control Training', 'Tracks infection control education or certification.', 'training', 12, 'AZ', 'Maricopa', null, true, 'mandatory', array[90, 60, 30]);

-- 6. TEST COMPLIANCE RECORDS
insert into user_compliance_items (
  user_id,
  compliance_item_id,
  location_state,
  location_county,
  completed_date,
  expires_date,
  status,
  reminder_enabled,
  next_reminder_date
)
values
(1, 1, 'AZ', 'Maricopa', '2025-01-01', '2026-01-01', 'active', true, '2025-10-03'),
(1, 2, 'AZ', 'Maricopa', '2024-06-01', '2026-06-01', 'active', true, '2026-03-03'),
(1, 3, 'AZ', 'Maricopa', '2024-01-01', '2025-01-01', 'expired', true, '2024-10-03'),
(1, 4, 'AZ', 'Maricopa', '2025-03-01', '2025-09-01', 'active', true, '2025-06-03');