create table if not exists members (
  id bigint generated by default as identity primary key,
  name text not null,
  email text
);

insert into members (name, email)
values ('Kristen', 'kristen@test.com');