create table user_compliance_items (
  id bigint generated by default as identity primary key,

  user_id bigint references members(id) on delete cascade,
  compliance_item_id bigint references compliance_items(id) on delete cascade,

  location_state text,
  location_county text,

  status text default 'active',

  completed_date date,
  expires_date date,

  reminder_enabled boolean default true,
  next_reminder_date date,

  created_at timestamptz default now()
);